services:
  mongo:
    image: mongo:latest
    container_name: xvpt-mongo
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_DATABASE=xvpt'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
    volumes:
      - mongo:/data/db
    networks:
      - xvpt
    restart: always

  redis:
    image: redis:latest
    container_name: xvpt-redis
    ports:
      - "6379:6379"
    networks:
      - xvpt
    restart: always

networks:
  xvpt:
    driver: bridge

volumes:
  mysql:
    driver: local
  mongo:
    driver: local