spring:
  application:
    name: xvpt
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/xvpt?authSource=admin
  security:
    jwt:
      key: ${JWT_KEY:asofhohoiv}
      expire: ${JWT_EXPIRE:14}
  servlet:
    multipart:
      max-file-size: 10MB

xvpt:
  file-store: ./xvpt
  account:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:password}